albums = {"in rainbows": "'everyone' likes this",
          "abbey road": "one guy has free feet on album cover",
          "loveless": "omg but the noise makes it good",
          "madvillainy": "every white hip hop guy's 'essential' (it is)",
          "in the aeroplane over the sea": "i just turned 20 and....this is deep",
          "vespertine": "omg how did you know i was bisexual??",
          "the velvet underground and nico": "omg how did you know i was bisexual....and old?",
          "kind of blue": "i just started listening to jazz and now i want to tell everyone how sophisticated i am",
          "LONG SEASON": "this whole album, or song is the literal definition of a blob (still peak)",
          "blonde": "'y-yeah i like this album whu won't anyone like this album why won't anyone like this guy?'",
          "igor":"you're either actually guy or youre a white rap fan",
          "dummy": "honestly can't diss you you're so cool....also i like this",
          "the money store": "i like these guys because they are soooooo quirky and 'industrial' (just learned that word existed)",
          "unknown pleasures": "my whole life is cope and i am decifing to romanticize it instead of face it (real)",
          "lift your skinny fists": "each song is like 20 minutes long but you have to UNDERSTAND it",
          "nevermind": "bro please be original" ,
          "blonde on blonde": "chat gpt generate me essential folk album i could use in conversation when women start talking about folk music to make them feel like i'm tapped in (i hate his voice here)",
          "grace":"youre either a teenage girl in love with him or a teenage girl in love with his music...also hallejujah ",
          "ants from up there":"chat gpt, generate the safest pick for aoty if i ever had to travel back to 2022 and someone asked me what was my favorite so far",
          "carrie and lowell": "about the death of someones parents so i cant say too much butbut no this music actually touches you",
          "selected ambient works":"you think not listening to skrillex and opting for this instead makes you intellegent",
          "hounds of love":"yeah youre either gay or like stranger things",
          "imaginal disk":"chat gpt, generate the safest pick for aoty if i ever had to travel back to 2025 and someone asked me what was my favorite so far",
          "either or":"im actually worried are u ok",
          "pet sounds":"you know almost nothing else about the beach boys",
          "the queen is dead":"you have to keep reminding yourself that you hate morissey before you listen to this",
          "disintegration": "bro and there are still zero goth baddies in your dms bro",
          "have a nice life":"988 Lifeline",
          "the velvet rope": "extremely based (you'll never guess)",
          "getting killed": "im so sad this isn't niche anymore (just got into the band post album drop)",
          "ziggy stardust": "easy to like this album and maskbeing bisexual",
          "lift yr skinny fists": "'this isnt a song this is an experience' ahh album",
          "souvlaki": "just because it isnt mbv doesnt mean its not basic",}
